### ISSUE TITLE
KSP 1.1.2 64bit Exception on launch

### ISSUE THREAD

**Issue by ghost** [SirDargon/ScienceContainers#7]
Only other mod is MM.

[ERR 19:12:58.377] AssemblyLoader: Exception loading 'ScienceContainers': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

Additional information about this exception:

 System.TypeLoadException: Could not load type 'ScienceContainers.CapsuleScienceContainer' from assembly 'ScienceContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'ScienceContainers.ProbeScienceContainer' from assembly 'ScienceContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<collectDataCoroutine>d__6' from assembly 'ScienceContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClassa' from assembly 'ScienceContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<collectDataCoroutine>d__a' from assembly 'ScienceContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClasse' from assembly 'ScienceContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by ghost** [comment]
Same output on 32bit

**Comment by RoxieCeleste** [comment]
That's because the last supported version by me was .90 and DMagic fixed it up to work with 1.0. This specific mod is no longer being maintained. Instead, I am working on a new mod that will incorporate what this did, plus more ([Science Hard Drives](https://github.com/SirDargon/ScienceHardDrives)). But I wouldn't suggest downloading that yet either as 1.1 completely destroyed it and I'm in the middle of a complete rewrite of it.
